@echo off
chcp 65001
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""طخود0135"" --option_ticker ""IROFIKCO9N21"" --expiration_date ""1404-01-06"" --strike_price 2800 --call_put p --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""طخود0136"" --option_ticker ""IROFIKCO9N31"" --expiration_date ""1404-01-06"" --strike_price 3000 --call_put p --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""طخود0137"" --option_ticker ""IROFIKCO9N41"" --expiration_date ""1404-01-06"" --strike_price 3250 --call_put p --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""طخود0138"" --option_ticker ""IROFIKCO9N51"" --expiration_date ""1404-01-06"" --strike_price 3500 --call_put p --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود0139"" --option_ticker ""IRO9IKCO8O91"" --expiration_date ""1404-01-06"" --strike_price 3750 --call_put c --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود0140"" --option_ticker ""IRO9IKCO8P01"" --expiration_date ""1404-01-06"" --strike_price 4000 --call_put c --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود0141"" --option_ticker ""IRO9IKCO8P11"" --expiration_date ""1404-01-06"" --strike_price 4500 --call_put c --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود0135"" --option_ticker ""IRO9IKCO8N21"" --expiration_date ""1404-01-06"" --strike_price 2800 --call_put c --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود0136"" --option_ticker ""IRO9IKCO8N31"" --expiration_date ""1404-01-06"" --strike_price 3000 --call_put c --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود0137"" --option_ticker ""IRO9IKCO8N41"" --expiration_date ""1404-01-06"" --strike_price 3250 --call_put c --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود0138"" --option_ticker ""IRO9IKCO8N51"" --expiration_date ""1404-01-06"" --strike_price 3500 --call_put c --can_trade_in_same_direction"
start cmd /k "python main.py --mode run --underlying_name ""خودرو"" --underlying_ticker ""IRO1IKCO0001"" --option_name ""ضخود2055"" --option_ticker ""IRO9IKCO8O21"" --expiration_date ""1404-02-03"" --strike_price 3000 --call_put c --can_trade_in_same_direction"
